### ISSUE TITLE
[Smoke test] Prosjektportalen 1.9.1 (Nye endringer)

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1502]
# 🧪 Smoke test for 1.9.1 (Nye endringer)

Vi tar for oss nye endringer som har kommet inn i denne versjonen. Dette issuet angår en `oppgradert` installasjon av Prosjektportalen 365.

## ✅ Oppsummert status for 1.9.1

Nye endringer
- Ny funksjonalitet: ✅ Ferdig, 02.05.24
- Feilrettinger: ✅ Ferdig, 03.05.24
- Forbedringer: ✅ Ferdig, 03.05.24

## 🍑 Nye endringer

Her listes endringer som er gjort i 1.9.1, disse punktene så langt det er mulig skal verifiseres.

### Ny funksjonalitet

- [x] Lagt til muligheten for et summeringsfelt i prosjektstatusseksjoner, denne kan summere eller finne gjennomsnitt av verdier basert på en kolonne i en liste- eller usikkerhetsseksjon Feil med summeringsfelt i prosjektstatusseksjoner #1485
  - [x] #1515
- [x] Lagt til mulighet for å legge til eller endre valg og verdier for idémodul, dette kan konfigureres med JSON i `Idékonfigurasjon` listen #1488
  - [x] #1516
- [x] Lagt til en aggregert oversikt for `Ressursallokering` i program og overordnet område mal #1490
  - [x] #1519

### Feilrettinger

- [x] Rettet et problem hvor listedata tilhørende tidligere prosjektstatusrapporter ikke ble hentet inn
  - #1472
- [x] Rettet et problem hvor 'Hooks' ikke ble kjørt riktig på grunn av manglende 'body' i `POST` forespørsel
  - #1479
- [x] Rettet et problem hvor dynamisk endring av prosjektforside via fasevelger ikke fungerte #1481
  - [x] #1521
- [x] Rettet et problem hvor noen underområder ikke var klikkbare i administrasjon av underområder webdel
  - #1468
- [x] Rettet et problem hvor URL til KUR-side ble feil ved godkjenning av en idé #1393
  - [x] #1520
- [x] Rettet et problem hvor `Gjør om til overordnet prosjekt` knapp ble igjen etter omgjøringen og at `Administrer underområder` knapp ikke lengre var synlig
  - #1412
- [x] Rettet et problem hvor `Vis alle målinger` ikke var synlig i `Gevinster for underområder` (Program/overordnet område)
  - #1461
- [x] Rettet et problem hvor 'Tittel' fra `Prosjektkolonner` listen ikke ble angitt som visningsnavn for felter i Prosjektinformasjon
  - #1458
- [x] Rettet et problem hvor kolonner var synlige i `Vis eller skjul kolonner` panelet på porteføljeoversikten selv om de skulle vært skjult
  - #1442
- [x] #1523
  - #1429
- [x] Rettet et problem hvor mapper ikke ble provisjonert dersom det eksisterte mapper med samme navn i prosjektet
  - #1497
- [x] Rettet et problem hvor tekstfeltet knyttet til `Fase` ikke ble riktig synkronisert til portefølje
  - #1492
- [x] Rettet et problem med visning av tallverdier i aggregerte oversikter hvor det ble lagt på en stor mengde desimaler
  - #1498
- [x] Rettet et problem hvor publiseringsikon ikke ble vist i historikk nedtrekksmeny for `Statusrapporter`
  - #1350
- [x] Rettet et problem hvor noen Idémodul listekommandoer ikke ble vist dersom andre Idé-lister var definert i `Idékonfigurasjon`
  - #1430
- [x] Rettet et problem hvor avviklede termer ble vist i nedtrekksmenyer for taksonomi felter
  - #1499
- [x] Rettet et problem hvor antall linjer angitt for et 'multi-linje' felt ikke ble reflektert i det nye redigeringspanelet
  - #1500
- [x] Rettet et problem hvor valuta ikke ble riktig sortert på porteføljeoversikt og andre aggregerte oversikter
  - #1369
- [x] Rettet et problem hvor eksportering av visninger som inneholdt felttypene 'valuta' og 'nummer' ble vist med masse desimaler
  - #1395
- [x] Rettet et problem med visning av 'valuta' felt-verdier i redigeringspaneler for prosjektstatus og prosjektinformasjon
  - #1503
- [x] Rettet et problem hvor visnings-id ikke la seg i URL feltet ved innlastning eller bytting av visninger i Porteføljeoversikt
  - #1355
- [x] Rettet et problem hvor visnings-id ikke la seg i URL feltet ved opprettelse av nye visninger, samt oppdatering av visningen (Porteføljeoversikter og andre aggregerte oversikter)
  - #1441
- [x] Rettet et problem hvor `Standardmal` ble satt som standard selvom andre maler var angitt som standard
  - #1471
- [x] Rettet et problem hvor taksonomifelt i redigeringspanel ikke støttet nivåer av termer
  - #1504
- [x] Rettet et problem hvor "Ansvarlig"-feltet i administrering av tiltak ikke viste personen som er valgt i feltet
  - #1506
- [x] Rettet et problem hvor det ikke var mulig å lagre tom verdi i valuta/tall felt fra redigeringspanel
  - #1510
- [x] Rettet et problem hvor lenke til prosjektets tidslinje ikke lenket riktig for program
  - #1511
- [x] Rettet et problem hvor Ja/Nei kolonner ble vist som 1/0 i filterpanel
  - #1522
- [x] Rettet et problem hvor migrering av tiltak feilet og frøs
  - #1524

### Forbedringer

- [x] Standard forhåndsvisning for migrerte tiltak (Tiltakshåndtering) er nå satt til 'Ingen forhåndsvisning'
  - #1480
- [x] Mulighet for å skru på/av informasjonsmelding for dynamisk hjemmeside, standard av
  - #1484
- [x] Tidslinjeliste baserer seg nå på område-id for å hente tidslinjeelementer, dette for å sikre at elementene hentes og vises riktig
  - #1477
- [x] Støtte for tallfelt i redigeringspaneler for prosjektstatus, prosjektinformasjon og tidslinje-liste
  - #1496
- [x] Forbedret ytelsen betraktelig og innlasting av store mengder prosjekter i prosjektutlisting webdel på forsiden av porteføljen
  - #1493
- [x] Forbedret filtreringsmuligheter for prosjekttidslinje på Porteføljenivå og Program/overordnet for underområder. Det er nå mulig å filtrere på prosjekter og prosjektinformasjon som er presisert i listen `Prosjektkolonner`
  - #1489
- [x] Oppdatert `Fasesider` prosjekttillegg til å støtte den nye vertikale inndeling
  - #1521
- [x] Dersom det er angitt et nytt navn til et prosjekt etter opprettelse blir dette nå synkronisert ned til porteføljen
  - #1518

⚠️ Dette issuet er en "work in progress", endringer kan forekomme.

**Comment by pzljanb** [comment]
Jeg tester på sites/PP365
