### ISSUE TITLE
Cleanup: Remove lists 'Information' and 'Milestones'

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#266]
## Description
Remove lists 'Information' and 'Milestones'.

## Todos
- [x] Remove list Information from JSON template
- [x] Remove list Milestones from JSON template
- [x] Remove content type Information from site scripts
- [x] Remove content type Milestones from site scripts

**Comment by okms** [comment]
I think there should be some context as to why Milestones and Information were removed @tarjeieo. Probably good reasons, but there are people asking why the lists were removed.
