### ISSUE TITLE
Release test - v1.2.3

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#313]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version 1.2.3

## Added

- [x] Descriptions on configuration page #301
- [x] New group "Porteføljeinnsyn". Grants users in this group insight into all projects in the portfolio #305
- [x] "Porteføljeinnsyn" button on configuration page for adding users to the group #306
- [x] Risk matrix toggle: Before and after risk reduction measures #293
- [x] Support for planner tasks references/attachments #287

## Fixed

- [x] View in portfolio overview was not changeable for non-admin users #308

- [x] Projects set to Avsluttet are no longer visible on the front page #307

## Changed

- [x] Disabled "Ny statusrapport" when a report is unpublished. #309

**Comment by pzljanb** [comment]
Mine tanker om denne alternative løsningen:
+Mye enklere å håndtere
+Stemmer også overens med Release notes i sin form
+"Godt nok" for testoversikten sin skyld
+Sitter og lurer på om det at testinfo "bor" i aktuell PR er det eneste riktige
Negativt med denne varianten
-Alle PR MÅ være referert i denne
-Tilsvarende må alle PR ha sin "how to test" del, men det bør de nok muligens uansett

**Comment by pzljanb** [comment]
Jeg stemmer for denne varianten.

Men mener også at det bør veie en god del om dere på utvikling @Remi749 har synspunkter som dreier seg i retning av at #312 er så mye lettere å håndtere at denne varianten ikke blir benyttet.

**Comment by pzljanb** [comment]
Testing performed with hub site:
- https://puzzlepart.sharepoint.com/sites/pp123/SitePages/Home.aspx
and projects:
- https://puzzlepart.sharepoint.com/sites/Lykkepillenmedlem
- https://puzzlepart.sharepoint.com/sites/Lykkepillen4/SitePages/ProjectHome.aspx
- https://puzzlepart.sharepoint.com/sites/Lykkepillenoffentlig/SitePages/ProjectHome.aspx

Tested completed and v1.2.3 could be released
