### ISSUE TITLE
Test av v1.2.4

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#347]
## Testing the new version before creating new release

Latest version can be found here: https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx
This site is upgraded automatically after push on dev branch.

Checklist for testing the additions, changes and fixes

# Version 1.2.4

## Added

- [x] Added "default" option for extensions, similar to list content #328
- [x] Added info message if there are unpublished statusreports #340
- [x] Added published/unpublished indicators for statusreports in dropdown and ribbon #341
- [x] Added possiblity to delete unpublished statusreports #343
- [x] Added PNG snapshot when publishing project status #337

## Fixed

- [x] Improved failure handling for PlannerConfiguration task in Project Setup #331
- [x] Support adding AD groups to get porfolio insights from SP group #332 #354 
- [x] Change to latest statusreport when creating a new statusreport #343
- [x] Issue were user couldn't exit the portfolio filter pane #355 
- [x] Wrong access settings #357

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

**Comment by pzljanb** [comment]
Issues registered when testing this release:
#348 Install Log
#349 Dispaly Name extensions
#350 Project status page not loading
#352 Portfolio content not limited to access level


Fix #331 tested by created 3 new projects in upgrade installastion, and 2 new projects in clean installation of PP365v124

**Comment by pzljanb** [comment]
Alle tester er utførte, og vi kan gå videre med frigivelse av 1.2.4

**Comment by tarjeieo** [comment]
Har testet den siste endringen vi la med, #357 i ny site og i eksisterende site.
