### ISSUE TITLE
Test av v1.2.6

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#391]
## Testing the new version before creating new release

Latest version can be found here: https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx
This site is upgraded automatically after push on dev branch.

Checklist for testing the additions, changes and fixes

# Version 1.2.6

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added
- [x] Added project template name to project properties #380  
- [x] Added support for phase sub text in phase selector #381 
- [x] Added support for navigation folders in document template picker #382
- [x] Added support for permission configuration using a configuration list on the hubsite #387 
- [x] Added Description field to Usikkerhet #410 
- [x] Enabled version history on Prosjektmaler list #359 

## Fixed

- [x] Fixes issues with single folder in "Hent dokumentmal" #376 
- [x] Issues with custom project fields #378 
- [x] Fix for visible check in project information web part #385 
- [x] Setting phase check list and planner task list as visible #389 
- [x] Flexible portfolio aggregation web part #395 
- [x] Copying for documents to new projects #399 
- [x] Fixes issues with more than one status report template #400 
- [x] Fixed issues with missing projects on the front page #364 
- [x] Fixed support for latest PnP PowerShell #377 

## Changed

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [x] Merge dev to main
    - [x] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
- [x] Build release
- [x] Test the new release from main
    - [x] Upgrade ['Prosjektportalen' tenant](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
        - [x] Further testing
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Our page
    - [ ] Roadmap

**Comment by olemp** [comment]
@pzljanb @tarjeieo Testing can begin ╰(°▽°)╯

**Comment by pzljanb** [comment]
@olemp; Is changelog updated with all issues/ PR's?

**Comment by olemp** [comment]
> @olemp; Is changelog updated with all issues/ PR's?

Yes. All testable PRs.

**Comment by pzljanb** [comment]
#377 Not tested ...

**Comment by olemp** [comment]
> #377 Not tested ...

I think it's tested by @tarjeieo

**Comment by pzljanb** [comment]
#364  to be tested within a installtion with a large number of projects
- [ ] Verified in installtaion : __________________

**Comment by pzljanb** [comment]
> > #377 Not tested ...
> 
> I think it's tested by @tarjeieo

@tarjeieo ; can you confirm testing/ verifiaction of this issue?

**Comment by tarjeieo** [comment]
Only thing left here @pzljanb is to inform users. Should we close this issue now?

**Comment by pzljanb** [comment]
> Only thing left here @pzljanb is to inform users. Should we close this issue now?

Inform @danielwiese and then close the issue.
We will then update 'Brukerforum' ++
