### ISSUE TITLE
Test av v1.2.7

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#453]
## Testing the new version before creating new release
Latest version can be found here: https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx
This site is upgraded automatically after push on dev branch.

Checklist for testing the additions, changes and fixes

# Version 1.2.7

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added
- [x] Added a new portfolio webpart, 'Prosjekttidslinje' for showcasing projects on a timeline #435
- [x] Added list 'Tidslinjeinnhold' to portfolio level #437 
- [x] Supporting pre-defined template setting #461

## Fixed
- [x] Avoiding overwrite of portfolio views, columns, column configuration and insights graphs on update #440
- [x] Overwriting configuration page to support new configuration links on update #425
- [x] Fixed portfolio overview crashing when default view was selected #428

## Changed
- [x] Changed Portfolio status view columns from "comments" to "status" #451
- [x] Improved project properties sync and fetching  #444 #449

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [ ] Merge dev to main
    - [ ] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)

- [ ] Build release
- [ ] Test the new release from main
    - [ ] Upgrade ['Prosjektportalen' tenant](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
        - [ ] Further testing
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Our page
    - [ ] Roadmap

**Comment by pzljanb** [comment]
@tarjeieo : #451 need a release not as follows:

## To release notes
- Changed Portfolio status view columns from "comments" to "status" #451:
For upgrade of existing installations you should consider the update behavior of the template.
This settings is set to "Skip" and for this reason the change of the portfolio status view wil not be applied.
For existing installations we recomend manual update of this view, or renaming the view BEFORE update of the installation.

**Comment by Remi749** [comment]
Added "Supporting pre-defined template setting #461" to "Added" list
