### ISSUE TITLE
Test av v1.2.9

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#511]
## Testing the new version before creating new release
Latest version can be found [HERE](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx)
This site is upgraded automatically after push on dev branch.
Checklist for testing the additions, changes and fixes

# Version 1.2.9

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added

- [x] Added multiline in list sections within Status Report #493
- [x] Added rich text and lineshift support #502 
- [x] Setting default site design for hub on install #492 

## Fixed
- [x] Fixed issue with property sync  #519 

## Changed

- [x] Converting SP dates to readable excel date format #495
- [x] Added description for site template #500

### Documentation
- [ ] Compare and approve [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md)
- [ ] Release notes verified

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [ ] Merge dev to main
    - [ ] Upgrade the internal [PZL initatives PP365 site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
    - [ ] Spot test changes from new release (do not add any testdata, only verify on existing data)

- [ ] Build release
- [ ] Test the new release from main
    - [ ] Upgrade ['Prosjektportalen' tenant](https://prosjektportalen.sharepoint.com/sites/pp365/SitePages/Home.aspx)
        - [ ] Test changes from new release
        - [ ] Generate new project
        - [ ] Verify correct behavior according to changes made to latest release
     - [ ] Install new release on clean site
        - [ ] Verify correct behavior according to changes made to latest release
        
- [ ] Inform
    - [ ] Produce post for reuse from template
    - [ ] Prosjektportalen brukerforum
    - [ ] Our webpage
    - [ ] Social media
    - [ ] Update existing content
         - [ ] ???
    - [ ] Merge updated user manual into master
