### ISSUE TITLE
Test og release av v1.3.0

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#534]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version 1.3.0
Testing to be performed on installation in: [Puzzlepart tenant](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx)
Note to issue creator: Example from changelog (remember to add checkboxes):

## Added

- [x] Added new multi-user field Prosjektstøtte #526
- [x] Added read-only project cards to project list #498 
- [x] Added "Avventer" as a new choice in Project LifeCycle #537 
- [x] Added a new project webpart 'Prosjekttidslinje' for showcasing projects and items for the current project on a timeline #497 
- [x] Added project tooltip when project in Porteføljeoversikt is not accessible #578 
- [x] Improved rendering of user fields in "Prosjektinformasjon" #576
 

## Fixed

- [x] Fixed UI bug by downgrading the office-ui-fabric-react package version to 6.214.0 #535 
- [x] Fixed redirect after creating a new project status #479  #530
- [x] Fixed project wizard bug when project is attached to another hub #532 
- [x]  Fixed wrong phases being displayed when switching between projects with different phases #520 

## Changed

- [x] Removed Home from Portfolio menu bar Issue #533
- [x] Removed list views and risk matrix from previous status reports #374 #531

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [x] Merge dev to main
    - [x] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)

- [x] Build release
- [x] Test the new release from main
    - [x] Upgrade ['Prosjektportalen' tenant](https://prosjektportalen.sharepoint.com/sites/pp365/SitePages/Home.aspx)
        - [ ] Further testing
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Nyhetsbrev for PP Assist-kunder
    - [ ] PP365 Nyhetsbrev
    - [ ] Our webpage (Sarah)
    - [ ] Linkedin (Sarah)
    - [ ] Roadmap (Jan)
    - [ ] ...

**Comment by pzljanb** [comment]
> #537 Tested partially OK
> 
> Avventer is a part of the project properties list, but other than that, it can't be found either as a field on the project properties list on the project home site, or as a filter available in Porteføljeoversikt.
> 
> I find a new view available for "Avventende prosjekter", but I think it should be included as a field in the properties list on project level as well.

The view "Avventende prosjekter" is manually created by me in our test environment, and is not part of the product.
Maybe it should be?

**Comment by tarjeieo** [comment]
> #537 Tested partially OK
> 
> Avventer is a part of the project properties list, but other than that, it can't be found either as a field on the project properties list on the project home site, or as a filter available in Porteføljeoversikt.
> 
> I find a new view available for "Avventende prosjekter", but I think it should be included as a field in the properties list on project level as well.

Agree that it should be a field in the project properties list, but this is another issue not necessary to include in 1.3.0

**Comment by tarjeieo** [comment]
> > > #537 Tested partially OK
> > > Avventer is a part of the project properties list, but other than that, it can't be found either as a field on the project properties list on the project home site, or as a filter available in Porteføljeoversikt.
> > > I find a new view available for "Avventende prosjekter", but I think it should be included as a field in the properties list on project level as well.
> > 
> > 
> > Agree that it should be a field in the project properties list, but this is another issue not necessary to include in 1.3.0
> 
> What does this mean? It's added as an option for a choice field now. What does it mean to add it as a field?

In the "Prosjektkolonner" list, to have it viewable, filterable in the portfolio

**Comment by olemp** [comment]
> > > > #537 Tested partially OK
> > > > Avventer is a part of the project properties list, but other than that, it can't be found either as a field on the project properties list on the project home site, or as a filter available in Porteføljeoversikt.
> > > > I find a new view available for "Avventende prosjekter", but I think it should be included as a field in the properties list on project level as well.
> > > 
> > > 
> > > Agree that it should be a field in the project properties list, but this is another issue not necessary to include in 1.3.0
> > 
> > 
> > What does this mean? It's added as an option for a choice field now. What does it mean to add it as a field?
> 
> In the "Prosjektkolonner" list, to have it viewable, filterable in the portfolio

But that's not related to the _Avventer_ option? Isn't that related to the project status field?

**Comment by tarjeieo** [comment]
> > > > > #537 Tested partially OK
> > > > > Avventer is a part of the project properties list, but other than that, it can't be found either as a field on the project properties list on the project home site, or as a filter available in Porteføljeoversikt.
> > > > > I find a new view available for "Avventende prosjekter", but I think it should be included as a field in the properties list on project level as well.
> > > > 
> > > > 
> > > > Agree that it should be a field in the project properties list, but this is another issue not necessary to include in 1.3.0
> > > 
> > > 
> > > What does this mean? It's added as an option for a choice field now. What does it mean to add it as a field?
> > 
> > 
> > In the "Prosjektkolonner" list, to have it viewable, filterable in the portfolio
> 
> But that's not related to the _Avventer_ option? Isn't that related to the project status field?

Indeed! That's why it will be a new issue not related/blockin 1.3.0
