### ISSUE TITLE
Test av v1.4.0

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#625]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version 1.4.0

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added

- [x] Added GtProjectLifecycleStatus in "Prosjektegenskaper" and as a filter in "Porteføljeoversikt" #587 #618

## Fixed

- [x] Fixed persistant filter checkbox on view change #545  #620
- [x] Fixed installation error with hidden fieldrefs #622 #623

## Changed

- [x] Added support for syncing number and currency fields in project properties #612
- [x] Added fix for not resetting portfolio navigation on upgrade #567 #613
- [x] Reformulated GtShowInPorfolio description to encompass more than uncertainties #615 #616 
- [x] Changed behavior when deleting a status report #597 #599
- [x] Changed behavior when deleting timeline item #569 #596 
- [x] Major changes implemented to project templates #594 #617  #619

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [x] Merge dev to main
    - [x] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)

- [x] Build release
- [ ] Test the new release from main
    - [ ] Upgrade ['Prosjektportalen' tenant](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
        - [ ] Further testing needed?
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Our page
    - [ ] Roadmap

**Comment by pzljanb** [comment]
Bug #631 identified on Konfigurasjon.aspx page
