### ISSUE TITLE
Test av v1.5.0

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#666]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version 1.5.0

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added

- [x] Added functionality for dynamic welcomepages based on project phases #643 
- [x] Added 'Vis alle egenskaper' button with panel to ProjectInformation webpart #650 
- [x] Added support for {site} token in Planner-tasks #646 
- [x] Add possibility to lock'project template configurations #645 
- [ ] Changed header in projectstatus report to show date when published instead of when created #654 
- [x] Supporting permission groups for specific project template #651 

## Fixed

- [ ] Fixed bug where ProjectTimeline would not load properly #661 
- [x] Fixed bug where Risks, Deliveries and Exp.Log would sometimes not #668 

## Changed

- [x] If there are no items in the list "Fasesjekkeliste". "Gå til fasesjekklisten" button won't show and the empty dialog when changing phase is skipped #660 

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [ ] Merge dev to main
    - [ ] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)

- [ ] Build release
- [ ] Test the new release from main
    - [ ] Upgrade ['Prosjektportalen' tenant](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
        - [ ] Further testing
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Our page
    - [ ] Roadmap

**Comment by pzljanb** [comment]
#682 Feil knyttet til statusrapporten

**Comment by pzljanb** [comment]
#661 Have not been able to test this. Since deleting of projects is locked by policy

**Comment by olemp** [comment]
Pre-release added https://github.com/Puzzlepart/prosjektportalen365/releases/tag/v1.5.0
