### ISSUE TITLE
Test av v1.5.0

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#667]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version X.X.X

Note to issue creator: Example from changelog (remember to add checkboxes):

## Added

- [ ] Added functionality for dynamic welcomepages based on project phases #643 
- [ ] Added 'Vis alle egenskaper' button with panel to ProjectInformation webpart #650 
- [ ] Added support for {site} token in Planner-tasks #646 
- [ ] Add possibility to lock'project template configurations #645 

## Fixed

- [ ] Fixed bug where ProjectTimeline would not load properly #661 

## Changed

- [ ] If there are no items in the list "Fasesjekkeliste". "Gå til fasesjekklisten" button won't show and the empty dialog when changing phase is skipped #660 

After everything has been checked and approved a release of the new version can be created. It is important that the changelog, this issue and the release notes are equal.

---

## Checklist when building a new release

- [ ] Merge dev to main
    - [ ] Upgrade the [internal 'Prosjektportalen' site](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)

- [ ] Build release
- [ ] Test the new release from main
    - [ ] Upgrade ['Prosjektportalen' tenant](https://pzlcloud.sharepoint.com/sites/ppintern/SitePages/Home.aspx)
        - [ ] Further testing
- [ ] Inform
    - [ ] Prosjektportalen brukerforum
    - [ ] Our page
    - [ ] Roadmap

**Comment by pzljanb** [comment]
Duplicate created. This issue "667should be closed.
While #666 is the one to use
